-- Phase 8: Operations support.
-- 1. Move demo deposit creation server-side so it's validated the same way
--    request_withdrawal() already is (deposit min/max, deposit_enabled,
--    maintenance mode) instead of trusting the client to only insert a
--    reasonable row.
-- 2. Mark transactions/notifications generated by the Activity Simulation
--    Engine so the UI can clearly label them as simulated (spec section 45).
-- 3. Realtime for announcements/maintenance so a banner change reaches
--    already-open sessions immediately.

alter table transactions add column is_simulated boolean not null default false;
alter table notifications add column is_simulated boolean not null default false;

create or replace function create_demo_deposit(p_amount numeric, p_currency text, p_network text)
returns deposits as $$
declare
  v_settings system_settings%rowtype;
  v_maintenance maintenance_settings%rowtype;
  v_deposit deposits%rowtype;
begin
  select * into v_settings from system_settings limit 1;
  select * into v_maintenance from maintenance_settings limit 1;

  if v_maintenance.enabled and v_maintenance.disable_deposits then
    raise exception 'deposits are temporarily disabled for maintenance';
  end if;

  if not v_settings.deposit_enabled then
    raise exception 'deposits are currently disabled';
  end if;

  if p_amount < v_settings.deposit_min or p_amount > v_settings.deposit_max then
    raise exception 'amount must be between % and %', v_settings.deposit_min, v_settings.deposit_max;
  end if;

  insert into deposits (user_id, amount, currency, network, provider, provider_reference, status)
  values (auth.uid(), p_amount, p_currency, p_network, 'demo', 'DEMO-' || gen_random_uuid(), 'pending')
  returning * into v_deposit;

  return v_deposit;
end;
$$ language plpgsql security definer set search_path = public;

grant execute on function create_demo_deposit to authenticated;

do $$
declare
  t text;
begin
  foreach t in array array['announcements', 'maintenance_settings'] loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = t
    ) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end $$;
